/* ============================================================================
 * PHASE 1 MOCK DATA — NOT APPLICATION DATA
 * ============================================================================
 *
 * Every record in `lib/mock-data/` is fabricated for UI visualisation. Nothing
 * here is real, nothing here is a claim about a real place, and nothing here
 * reaches a network.
 *
 * ---------------------------------------------------------------------------
 * REPLACEMENT PLAN
 * ---------------------------------------------------------------------------
 * Phase 1  this file. Components import `@/lib/mock-data` and nothing else.
 * Phase 2  the session is real. `SessionProvider` starts reading a real user.
 * Phase 3  `services/incidents` + `GET /api/incidents`. Swap the source of
 *          `useMockIncidents()` for the RSC fetch; the `Incident` TYPE does not
 *          change, so no component changes.
 * Phase 4  `services/ai` produces the real triage fields on the same shape.
 * Phase 5  real `media[].previewUrl` values become signed Storage URLs.
 * Phase 6  `IncidentMap` swaps its projection for the Google Maps SDK. The
 *          component's props do not change.
 * Phase 8  `useRealtimeIncidents` replaces the static array; the shape and the
 *          row components are already written for a live patch.
 *
 * ---------------------------------------------------------------------------
 * WHAT MUST NEVER HAPPEN
 * ---------------------------------------------------------------------------
 * A mock value must not be imported by anything under `services/`, and a real
 * value must never be invented to fill a mock gap. If a screen looks wrong, fix
 * the mock — do not paper over it. `scripts/check-no-mock-in-services` (Phase 3)
 * enforces the first rule.
 *
 * ---------------------------------------------------------------------------
 * DEMO DATASET
 * ---------------------------------------------------------------------------
 * Anchored to the coordinates in docs/29_DEMO_SCENARIO.md (Secunderabad, ~17.44
 * N 78.48 E) so that the demo dataset and the documentation describe the same
 * city. Times are ISO-8601 UTC and are all anchored to DEMO_NOW
 * (2026-09-26T10:12:00Z) so ages render identically on every run.
 * ========================================================================= */

import type {
  Analytics,
  AppNotification,
  AuditEntry,
  DashboardTiles,
  Dispatch,
  DispatchCandidate,
  HistoryEvent,
  Incident,
  IncidentReport,
  Responder,
  SystemHealth,
  User,
} from '@/types/domain';
import type { UserRole } from '@/types/enums';

const NOW = Date.parse('2026-09-26T10:12:00.000Z');
const MIN = 60_000;

/** `n` minutes before the demo clock. Keeps every timestamp self-consistent. */
function ago(minutes: number): string {
  return new Date(NOW - minutes * MIN).toISOString();
}

/* -------------------------------------------------------------------------- */
/* Users                                                                      */
/* -------------------------------------------------------------------------- */

export const MOCK_CURRENT_USER_UID = 'u_disp01';

export const MOCK_USERS: readonly User[] = [
  {
    uid: 'u_adm001',
    email: 'arun@example.com',
    emailVerified: true,
    displayName: 'Arun Patel',
    photoURL: null,
    role: 'admin',
    status: 'active',
    provider: 'password',
    createdAt: ago(60 * 24 * 41),
    lastLoginAt: ago(12),
  },
  {
    uid: 'u_disp01',
    email: 'meera@example.com',
    emailVerified: true,
    displayName: 'Meera Rao',
    photoURL: null,
    role: 'dispatcher',
    status: 'active',
    provider: 'google',
    createdAt: ago(60 * 24 * 38),
    lastLoginAt: ago(2),
  },
  {
    uid: 'u_disp02',
    email: 'daniel@example.com',
    emailVerified: true,
    displayName: 'Daniel Okoro',
    photoURL: null,
    role: 'dispatcher',
    status: 'active',
    provider: 'password',
    createdAt: ago(60 * 24 * 30),
    lastLoginAt: ago(180),
  },
  {
    uid: 'u_4Kd8sTn',
    email: 'yusuf@example.com',
    emailVerified: true,
    displayName: 'Yusuf Khan',
    photoURL: null,
    role: 'responder',
    status: 'active',
    provider: 'google',
    createdAt: ago(60 * 24 * 26),
    lastLoginAt: ago(1),
  },
  {
    uid: 'u_7Hq2Bd',
    email: 'sara@example.com',
    emailVerified: true,
    displayName: 'Sara Iqbal',
    photoURL: null,
    role: 'responder',
    status: 'active',
    provider: 'password',
    createdAt: ago(60 * 24 * 22),
    lastLoginAt: ago(4),
  },
  {
    uid: 'u_2Ww9Kz',
    email: 'ravi@example.com',
    emailVerified: true,
    displayName: 'Ravi Menon',
    photoURL: null,
    role: 'responder',
    status: 'active',
    provider: 'password',
    createdAt: ago(60 * 3),
    lastLoginAt: ago(22),
  },
  {
    uid: 'u_5Tr8Nm',
    email: 'deepa@example.com',
    emailVerified: true,
    displayName: 'Deepa Sharma',
    photoURL: null,
    role: 'responder',
    status: 'pending_verification',
    provider: 'password',
    createdAt: ago(60 * 30),
    lastLoginAt: ago(60 * 30),
  },
  {
    uid: 'u_1Li4Op',
    email: 'kiran@example.com',
    emailVerified: false,
    displayName: 'K. Iyer',
    photoURL: null,
    role: 'responder',
    status: 'pending_verification',
    provider: 'password',
    createdAt: ago(60 * 8),
    lastLoginAt: ago(60 * 8),
  },
  {
    uid: 'u_9fJ2kLmQ',
    email: 'priya@example.com',
    emailVerified: true,
    displayName: 'Priya Nair',
    photoURL: null,
    role: 'citizen',
    status: 'active',
    provider: 'google',
    createdAt: ago(60 * 12),
    lastLoginAt: ago(6),
  },
  {
    uid: 'u_3Nm6Xc',
    email: 'imran@example.com',
    emailVerified: true,
    displayName: 'Imran Sheikh',
    photoURL: null,
    role: 'citizen',
    status: 'active',
    provider: 'password',
    createdAt: ago(60 * 9),
    lastLoginAt: ago(190),
  },
  {
    uid: 'u_8Vb1Ry',
    email: 'suspended@example.com',
    emailVerified: true,
    displayName: 'Former Member',
    photoURL: null,
    role: 'citizen',
    status: 'suspended',
    provider: 'password',
    createdAt: ago(60 * 60),
    lastLoginAt: ago(60 * 24 * 9),
  },
];

/* -------------------------------------------------------------------------- */
/* Incidents                                                                  */
/* -------------------------------------------------------------------------- */

/** The demo cluster sits on the same geohash-6 cell (docs/29 §dataset). */
const METRO_GATE = { lat: 17.4478, lng: 78.4874 } as const;
const MARKET = { lat: 17.4502, lng: 78.4931 } as const;
const LAKE_EDGE = { lat: 17.4412, lng: 78.4798 } as const;

function gps(lat: number, lng: number, accuracyM: number) {
  return {
    lat,
    lng,
    accuracyM,
    accuracyGrade: (accuracyM <= 50 ? 'high' : accuracyM <= 200 ? 'medium' : 'low') as
      | 'high'
      | 'medium'
      | 'low',
    source: 'gps' as const,
    placeName: null,
  };
}

export const MOCK_INCIDENTS: readonly Incident[] = [
  /* --- The demo incident: a critical road accident, fully progressed ------- */
  {
    incidentId: 'r7Kp2mQ9xL4nT8vB3cD6',
    reference: 'CG-7QK4M2',
    status: 'assigned',
    category: 'traffic_accident',
    urgency: 'critical',
    urgencySource: 'ai',
    triageSource: 'ai',
    aiConfidence: 0.83,
    aiNeedsReview: false,
    summary:
      'Two-car collision blocking the right lane; one person trapped inside the second car.',
    originalText:
      'big accident on the service road near the metro gate, a car is stuck and someone is crying inside, please send help fast',
    peopleAffected: 2,
    requiredResources: [
      { resourceId: 'res_ambulance', quantity: 1, confidence: 0.81, source: 'ai' },
      { resourceId: 'res_fire_engine', quantity: 1, confidence: 0.72, source: 'ai' },
    ],
    safetyFlags: ['medical_critical', 'injured_trapped'],
    location: {
      ...gps(METRO_GATE.lat, METRO_GATE.lng, 34),
      placeName: 'Service Road, near Secunderabad Metro Gate 1',
    },
    reporterCount: 2,
    linkedReportCount: 1,
    evidenceCount: 3,
    verification: 'human',
    duplicateStatus: 'confirmed_duplicate',
    duplicateOf: null,
    assignee: { uid: 'u_4Kd8sTn', displayName: 'Yusuf Khan', status: 'busy' },
    slaTargetMin: 5,
    slaState: 'on_track',
    ageMin: 4,
    distanceM: null,
    channel: 'app',
    createdAt: ago(4),
    updatedAt: ago(1),
    verifiedAt: ago(3),
    respondedAt: ago(1),
    arrivedAt: null,
    resolvedAt: null,
    closedAt: null,
    deletedAt: null,
    deletedBy: null,
    deleteReason: null,
    resolutionCode: null,
    resolutionNote: null,
  },

  /* --- Unassigned fire, high urgency, needs review (low AI confidence) ----- */
  {
    incidentId: 'r2Fw8nT4vX6mZ1qB9dK3',
    reference: 'CG-3PL8QW',
    status: 'triaged',
    category: 'fire',
    urgency: 'high',
    urgencySource: 'ai',
    triageSource: 'ai',
    aiConfidence: 0.54,
    aiNeedsReview: true,
    summary: 'Smoke reported from a ground-floor shop; cause not stated in the report.',
    originalText: 'lots of smoke coming out of a shop near the market, not sure if fire yet',
    peopleAffected: null,
    requiredResources: [
      { resourceId: 'res_fire_extinguisher_team', quantity: 1, confidence: 0.48, source: 'ai' },
    ],
    safetyFlags: ['fire', 'low_confidence'],
    location: {
      ...gps(MARKET.lat, MARKET.lng, 420),
      placeName: 'Gaddiannaram Market Road',
    },
    reporterCount: 1,
    linkedReportCount: 0,
    evidenceCount: 1,
    verification: 'ai',
    duplicateStatus: 'potential_duplicate',
    duplicateOf: {
      incidentId: 'r9Lp3vX7bN2mQ5tC8dF1',
      reference: 'CG-9ZZ1QP',
      score: 0.78,
    },
    assignee: null,
    slaTargetMin: 15,
    slaState: 'at_risk',
    ageMin: 9,
    distanceM: null,
    channel: 'app',
    createdAt: ago(9),
    updatedAt: ago(7),
    verifiedAt: null,
    respondedAt: null,
    arrivedAt: null,
    resolvedAt: null,
    closedAt: null,
    deletedAt: null,
    deletedBy: null,
    deleteReason: null,
    resolutionCode: null,
    resolutionNote: null,
  },

  /* --- SLA breached: rising water, unassigned, no location ------------------ */
  {
    incidentId: 'r5Hj1vN8qC3mZ7tB2wE9',
    reference: 'CG-9ZZ1QP',
    status: 'verified',
    category: 'flood',
    urgency: 'high',
    urgencySource: 'ai',
    triageSource: 'ai',
    aiConfidence: 0.71,
    aiNeedsReview: false,
    summary: 'Water level rising on the lakeside road; two vehicles stalled.',
    originalText:
      'road near the lake is flooding fast, two cars stuck in water, people standing on the divider',
    peopleAffected: 2,
    requiredResources: [{ resourceId: 'res_water_rescue', quantity: 1, confidence: 0.66, source: 'ai' }],
    safetyFlags: ['flood_rising'],
    location: {
      ...gps(LAKE_EDGE.lat, LAKE_EDGE.lng, 88),
      placeName: 'Lakeside Road, near the pedestrian bridge',
    },
    reporterCount: 3,
    linkedReportCount: 2,
    evidenceCount: 4,
    verification: 'human',
    duplicateStatus: 'none',
    duplicateOf: null,
    assignee: null,
    slaTargetMin: 15,
    slaState: 'breached',
    ageMin: 34,
    distanceM: null,
    channel: 'app',
    createdAt: ago(34),
    updatedAt: ago(21),
    verifiedAt: ago(30),
    respondedAt: null,
    arrivedAt: null,
    resolvedAt: null,
    closedAt: null,
    deletedAt: null,
    deletedBy: null,
    deleteReason: null,
    resolutionCode: null,
    resolutionNote: null,
  },

  /* --- LOCATION UNKNOWN: the state that must be visible, not hidden --------- */
  {
    incidentId: 'r8Qw4zX1mV6nB2kD9sF3',
    reference: 'CG-4RT8W',
    status: 'new',
    category: 'medical',
    urgency: 'critical',
    urgencySource: 'ai',
    triageSource: 'fallback',
    aiConfidence: 0.31,
    aiNeedsReview: true,
    summary: 'Automated triage only. A person needs to read the original report.',
    originalText: 'my father collapsed near the temple he cannot speak please send someone',
    peopleAffected: 1,
    requiredResources: [],
    safetyFlags: ['medical_critical', 'low_confidence', 'unclear_location'],
    location: null,
    reporterCount: 1,
    linkedReportCount: 0,
    evidenceCount: 0,
    verification: 'fallback',
    duplicateStatus: 'none',
    duplicateOf: null,
    assignee: null,
    slaTargetMin: 5,
    slaState: 'at_risk',
    ageMin: 2,
    distanceM: null,
    channel: 'app',
    createdAt: ago(2),
    updatedAt: ago(2),
    verifiedAt: null,
    respondedAt: null,
    arrivedAt: null,
    resolvedAt: null,
    closedAt: null,
    deletedAt: null,
    deletedBy: null,
    deleteReason: null,
    resolutionCode: null,
    resolutionNote: null,
  },

  /* --- Heatwave cluster (4 incidents in one cell, for analytics) ------------ */
  ...(
    [
      {
        id: 'r1Ab2Cd3Ef4Gh5Ij6Kl7',
        ref: 'CG-HW1001',
        cat: 'heatwave' as const,
        summary: 'Heat exhaustion reported; person resting in shade.',
        people: 1,
        age: 96,
        acc: 65,
        urgency: 'medium' as const,
        state: 'resolved' as const,
      },
      {
        id: 'r2Bc3De4Fg5Hi6Kj7Lm8',
        ref: 'CG-HW1002',
        cat: 'heatwave' as const,
        summary: 'Older resident found confused on a footpath during peak heat.',
        people: 1,
        age: 118,
        acc: 51,
        urgency: 'medium' as const,
        state: 'closed' as const,
      },
      {
        id: 'r3Cd4Ef5Gh6Ij7Kl8Mn9',
        ref: 'CG-HW1003',
        cat: 'heatwave' as const,
        summary: 'Construction worker reporting dizziness; water requested.',
        people: 1,
        age: 141,
        acc: 33,
        urgency: 'low' as const,
        state: 'resolved' as const,
      },
      {
        id: 'r4De5Fh6Hi7Jk8Lm9Np0',
        cat: 'infrastructure' as const,
        ref: 'CG-IN2001',
        summary: 'Transformer pole down on the main road; area without power.',
        people: null,
        age: 205,
        acc: 27,
        urgency: 'medium' as const,
        state: 'on_scene' as const,
      },
    ] as const
  ).map<Incident>((row) => ({
    incidentId: row.id,
    reference: row.ref,
    status: row.state,
    category: row.cat,
    urgency: row.urgency,
    urgencySource: 'ai',
    triageSource: 'ai',
    aiConfidence: 0.76,
    aiNeedsReview: false,
    summary: row.summary,
    originalText: row.summary.toLowerCase(),
    peopleAffected: row.people,
    requiredResources: [],
    safetyFlags: row.cat === 'heatwave' ? ['medical_critical'] : [],
    location: {
      lat: 17.4451 + row.acc / 10000,
      lng: 78.4831 + row.acc / 10000,
      accuracyM: 40,
      accuracyGrade: 'high',
      source: 'gps',
      placeName: 'Gaddiannaram, Secunderabad',
    },
    reporterCount: 1,
    linkedReportCount: 0,
    evidenceCount: 0,
    verification: row.state === 'on_scene' ? 'human' : 'ai',
    duplicateStatus: 'none',
    duplicateOf: null,
    assignee: row.state === 'on_scene' ? { uid: 'u_7Hq2Bd', displayName: 'Sara Iqbal', status: 'busy' } : null,
    slaTargetMin: row.urgency === 'medium' ? 60 : 240,
    slaState: 'on_track',
    ageMin: row.age,
    distanceM: null,
    channel: 'app',
    createdAt: ago(row.age),
    updatedAt: ago(Math.max(1, row.age - 6)),
    verifiedAt: ago(Math.max(1, row.age - 2)),
    respondedAt: null,
    arrivedAt: null,
    resolvedAt: row.state === 'resolved' || row.state === 'closed' ? ago(Math.max(1, row.age - 20)) : null,
    closedAt: row.state === 'closed' ? ago(Math.max(1, row.age - 30)) : null,
    deletedAt: null,
    deletedBy: null,
    deleteReason: null,
    resolutionCode: row.state === 'resolved' ? 'resolved_safe' : null,
    resolutionNote: null,
  })),

  /* --- A soft-deleted record so /admin/incidents is not empty -------------- */
  {
    incidentId: 'r6Yz0aB1cD2eF3gH4iJ5',
    reference: 'CG-1AB2CD',
    status: 'cancelled',
    category: 'community_aid',
    urgency: 'low',
    urgencySource: 'human',
    triageSource: 'ai',
    aiConfidence: 0.44,
    aiNeedsReview: true,
    summary: 'Water request that was a duplicate of an earlier aid report.',
    originalText: 'need drinking water for the old people on the second floor',
    peopleAffected: 6,
    requiredResources: [{ resourceId: 'res_food_water_kit', quantity: 2, confidence: 0.5, source: 'reporter' }],
    safetyFlags: ['low_confidence'],
    location: { ...gps(17.4521, 78.4811, 120), placeName: 'Balkampet' },
    reporterCount: 1,
    linkedReportCount: 0,
    evidenceCount: 0,
    verification: 'human',
    duplicateStatus: 'confirmed_duplicate',
    duplicateOf: { incidentId: 'r4De5Fh6Hi7Jk8Lm9Np0', reference: 'CG-IN2001', score: 0.62 },
    assignee: null,
    slaTargetMin: 240,
    slaState: 'on_track',
    ageMin: 430,
    distanceM: null,
    channel: 'app',
    createdAt: ago(430),
    updatedAt: ago(400),
    verifiedAt: null,
    respondedAt: null,
    arrivedAt: null,
    resolvedAt: null,
    closedAt: null,
    deletedAt: ago(395),
    deletedBy: 'u_disp01',
    deleteReason: 'Duplicate of CG-IN2001, entered in error',
    resolutionCode: null,
    resolutionNote: null,
  },
];

/* -------------------------------------------------------------------------- */
/* Reports + history for the demo incident                                     */
/* -------------------------------------------------------------------------- */

export const MOCK_REPORTS_BY_INCIDENT: Readonly<Record<string, readonly IncidentReport[]>> = {
  r7Kp2mQ9xL4nT8vB3cD6: [
    {
      reportId: 'rep_8Dn2Kq',
      kind: 'original',
      reporter: { uid: 'u_9fJ2kLmQ', displayName: 'Priya Nair' },
      text: 'big accident on the service road near the metro gate, a car is stuck and someone is crying inside, please send help fast',
      createdAt: ago(4),
      similarityToPrimary: null,
      media: [
        {
          mediaId: 'med_a91',
          kind: 'image',
          contentType: 'image/jpeg',
          sizeBytes: 184320,
          width: 1280,
          height: 960,
          durationSec: null,
          previewUrl: null,
          scanStatus: 'clean',
        },
        {
          mediaId: 'med_a92',
          kind: 'image',
          contentType: 'image/jpeg',
          sizeBytes: 201_984,
          width: 1600,
          height: 1200,
          durationSec: null,
          previewUrl: null,
          scanStatus: 'clean',
        },
        {
          mediaId: 'med_a93',
          kind: 'audio',
          contentType: 'audio/webm',
          sizeBytes: 320_512,
          width: null,
          height: null,
          durationSec: 41,
          previewUrl: null,
          scanStatus: 'clean',
        },
      ],
    },
    {
      reportId: 'rep_9Fo3Lr',
      kind: 'duplicate_link',
      reporter: { uid: 'u_3Nm6Xc', displayName: 'Imran Sheikh' },
      text: 'same accident here, 2 cars, one person stuck inside the silver car',
      createdAt: ago(1),
      similarityToPrimary: 0.68,
      media: [],
    },
  ],
};

export const MOCK_HISTORY_BY_INCIDENT: Readonly<Record<string, readonly HistoryEvent[]>> = {
  r7Kp2mQ9xL4nT8vB3cD6: [
    {
      eventId: 'ev_1',
      eventType: 'created',
      fromStatus: null,
      toStatus: 'new',
      actor: { uid: 'u_9fJ2kLmQ', displayName: 'Priya Nair', role: 'citizen' },
      reason: null,
      note: null,
      metadata: { channel: 'app', evidenceCount: 1 },
      requestId: 'req_7Kd2mQ9xL4n',
      createdAt: ago(4),
    },
    {
      eventId: 'ev_2',
      eventType: 'ai_triaged',
      fromStatus: 'new',
      toStatus: 'triaged',
      actor: { uid: 'system', displayName: 'CareGrid AI', role: 'system' },
      reason: null,
      note: null,
      metadata: { confidence: 0.83, urgency: 'critical', category: 'traffic_accident', fallback: false },
      requestId: 'req_7Kd2mQ9xL4n',
      createdAt: ago(4),
    },
    {
      eventId: 'ev_3',
      eventType: 'evidence_added',
      fromStatus: 'triaged',
      toStatus: 'triaged',
      actor: { uid: 'u_9fJ2kLmQ', displayName: 'Priya Nair', role: 'citizen' },
      reason: null,
      note: 'Added a second photo',
      metadata: { mediaCount: 3 },
      requestId: 'req_9Rt1nB4vC6m',
      createdAt: ago(3.6),
    },
    {
      eventId: 'ev_4',
      eventType: 'verified',
      fromStatus: 'triaged',
      toStatus: 'verified',
      actor: { uid: 'u_disp01', displayName: 'Meera Rao', role: 'dispatcher' },
      reason: null,
      note: 'Collision confirmed from the photo. Trapped casualty reported.',
      metadata: null,
      requestId: 'req_2Wx8pL0mN4q',
      createdAt: ago(3),
    },
    {
      eventId: 'ev_5',
      eventType: 'merged_in',
      fromStatus: 'triaged',
      toStatus: 'triaged',
      actor: { uid: 'u_disp01', displayName: 'Meera Rao', role: 'dispatcher' },
      reason: 'Same collision, reported twice 3 minutes apart',
      note: null,
      metadata: { distanceM: 142, textSimilarity: 0.68 },
      requestId: 'req_5Yc7uI9oP1r',
      createdAt: ago(2.4),
    },
    {
      eventId: 'ev_6',
      eventType: 'assigned',
      fromStatus: 'verified',
      toStatus: 'assigned',
      actor: { uid: 'u_disp01', displayName: 'Meera Rao', role: 'dispatcher' },
      reason: null,
      note: 'Nearest verified responder with ambulance capability.',
      metadata: { distanceM: 640, capabilityMatch: true },
      requestId: 'req_8Ab2dF4hJ6k',
      createdAt: ago(2.2),
    },
    {
      eventId: 'ev_7',
      eventType: 'status_change',
      fromStatus: 'assigned',
      toStatus: 'en_route',
      actor: { uid: 'u_4Kd8sTn', displayName: 'Yusuf Khan', role: 'responder' },
      reason: null,
      note: 'En route. 640 m.',
      metadata: null,
      requestId: 'req_3Gh6jK8lM0n',
      createdAt: ago(1),
    },
  ],
};

/* -------------------------------------------------------------------------- */
/* Responders + dispatches                                                    */
/* -------------------------------------------------------------------------- */

export const MOCK_RESPONDERS: readonly Responder[] = [
  {
    uid: 'u_4Kd8sTn',
    displayName: 'Yusuf Khan',
    status: 'busy',
    verification: 'verified',
    capabilities: ['res_ambulance', 'res_first_aid'],
    serviceRadiusM: 5000,
    activeIncidentCount: 1,
    maxConcurrentIncidents: 1,
    lastLocationAt: ago(0.3),
    lastLocationAccuracyGrade: 'high',
    submittedAt: ago(60 * 26),
    staleLocation: false,
    location: { ...gps(17.4491, 78.4901, 22), placeName: null },
    activeIncidentId: 'r7Kp2mQ9xL4nT8vB3cD6',
    phone: '+919876543210',
    stats: { totalAssignments: 34, acceptedAssignments: 31, avgResponseSec: 214 },
    verificationNote: 'First-aid certification verified (ID 44-2210)',
    certifications: [
      { name: 'EMT-B', expiresAt: ago(-60 * 24 * 220) },
      { name: 'BLS', expiresAt: ago(-60 * 24 * 90) },
    ],
  },
  {
    uid: 'u_7Hq2Bd',
    displayName: 'Sara Iqbal',
    status: 'busy',
    verification: 'verified',
    capabilities: ['res_fire_extinguisher_team', 'res_first_aid'],
    serviceRadiusM: 8000,
    activeIncidentCount: 1,
    maxConcurrentIncidents: 2,
    lastLocationAt: ago(1.1),
    lastLocationAccuracyGrade: 'high',
    submittedAt: ago(60 * 22),
    staleLocation: false,
    location: { ...gps(17.4512, 78.4944, 31), placeName: null },
    activeIncidentId: 'r4De5Fh6Hi7Jk8Lm9Np0',
    phone: '+919812340000',
    stats: { totalAssignments: 21, acceptedAssignments: 20, avgResponseSec: 262 },
    verificationNote: 'Fire team lead, station 4',
    certifications: [{ name: 'Fire Suppression', expiresAt: ago(-60 * 24 * 300) }],
  },
  {
    uid: 'u_2Ww9Kz',
    displayName: 'Ravi Menon',
    status: 'available',
    verification: 'verified',
    capabilities: ['res_traffic_control', 'res_heavy_tow'],
    serviceRadiusM: 6000,
    activeIncidentCount: 0,
    maxConcurrentIncidents: 1,
    lastLocationAt: ago(2.4),
    lastLocationAccuracyGrade: 'medium',
    submittedAt: ago(60 * 30),
    staleLocation: false,
    location: { ...gps(17.4561, 78.4866, 96), placeName: null },
    activeIncidentId: null,
    phone: '+919845670000',
    stats: { totalAssignments: 12, acceptedAssignments: 10, avgResponseSec: 388 },
    verificationNote: 'Traffic marshalling certificate checked',
    certifications: [{ name: 'Traffic Marshalling', expiresAt: ago(-60 * 24 * 45) }],
  },
  {
    uid: 'u_5Tr8Nm',
    displayName: 'Deepa Sharma',
    status: 'available',
    verification: 'pending',
    capabilities: ['res_ambulance', 'res_first_aid'],
    serviceRadiusM: 5000,
    activeIncidentCount: 0,
    maxConcurrentIncidents: 1,
    lastLocationAt: ago(4),
    lastLocationAccuracyGrade: 'medium',
    submittedAt: ago(60 * 30),
    staleLocation: false,
    location: { ...gps(17.4431, 78.4912, 74), placeName: null },
    activeIncidentId: null,
    phone: '+919788990000',
    stats: { totalAssignments: 0, acceptedAssignments: 0, avgResponseSec: null },
    verificationNote: null,
    certifications: [
      { name: 'EMT-B', expiresAt: ago(-60 * 24 * 160) },
      { name: 'BLS', expiresAt: ago(-60 * 24 * 30) },
    ],
  },
  {
    uid: 'u_1Li4Op',
    displayName: 'K. Iyer',
    status: 'offline',
    verification: 'pending',
    capabilities: ['res_water_rescue'],
    serviceRadiusM: 4000,
    activeIncidentCount: 0,
    maxConcurrentIncidents: 1,
    // Older than STALE_LOCATION_MIN — must render as a stale location, and be
    // sorted last in the candidate list (US-022 AC2).
    lastLocationAt: ago(22),
    lastLocationAccuracyGrade: 'low',
    submittedAt: ago(60 * 8),
    staleLocation: true,
    location: { ...gps(17.4401, 78.4822, 320), placeName: null },
    activeIncidentId: null,
    phone: null,
    stats: { totalAssignments: 0, acceptedAssignments: 0, avgResponseSec: null },
    verificationNote: null,
    certifications: [{ name: 'Water Safety', expiresAt: null }],
  },
];

export const MOCK_DISPATCHES: readonly Dispatch[] = [
  {
    dispatchId: 'dsp_2Qm8Kx',
    incidentId: 'r7Kp2mQ9xL4nT8vB3cD6',
    incidentReference: 'CG-7QK4M2',
    responder: { uid: 'u_4Kd8sTn', displayName: 'Yusuf Khan', status: 'busy' },
    dispatchedBy: 'u_disp01',
    mode: 'manual',
    status: 'accepted',
    distanceM: 640,
    etaSec: 180,
    capabilityMatch: true,
    note: 'Use the service road gate; southbound lane blocked.',
    responseSec: 47,
    dispatchedAt: ago(2.2),
    acceptedAt: ago(2.1),
    expiresAt: ago(0.2),
    completedAt: null,
  },
  {
    dispatchId: 'dsp_3Tn9Ly',
    incidentId: 'r4De5Fh6Hi7Jk8Lm9Np0',
    incidentReference: 'CG-IN2001',
    responder: { uid: 'u_7Hq2Bd', displayName: 'Sara Iqbal', status: 'busy' },
    dispatchedBy: 'u_disp01',
    mode: 'manual',
    status: 'accepted',
    distanceM: 2100,
    etaSec: 420,
    capabilityMatch: false,
    note: null,
    responseSec: 61,
    dispatchedAt: ago(190),
    acceptedAt: ago(189),
    expiresAt: ago(188),
    completedAt: null,
  },
  {
    dispatchId: 'dsp_4Uo0Mz',
    incidentId: 'r2Fw8nT4vX6mZ1qB9dK3',
    incidentReference: 'CG-3PL8QW',
    responder: { uid: 'u_2Ww9Kz', displayName: 'Ravi Menon', status: 'available' },
    dispatchedBy: 'u_disp01',
    mode: 'auto_suggest',
    status: 'withdrawn',
    distanceM: 1450,
    etaSec: 300,
    capabilityMatch: false,
    note: 'Traffic control, not fire.',
    responseSec: null,
    dispatchedAt: ago(8),
    acceptedAt: null,
    expiresAt: ago(6),
    completedAt: null,
  },
];

export const MOCK_DISPATCH_CANDIDATES: readonly DispatchCandidate[] = [
  {
    responder: {
      uid: 'u_2Ww9Kz',
      displayName: 'Ravi Menon',
      status: 'available',
      capabilities: ['res_traffic_control', 'res_heavy_tow'],
      activeIncidentCount: 0,
    },
    location: { lat: 17.4561, lng: 78.4866 },
    distanceM: 1450,
    etaSec: 300,
    capabilityMatch: false,
    missingResources: ['res_fire_extinguisher_team'],
    staleLocation: false,
    rank: 1,
  },
  {
    responder: {
      uid: 'u_7Hq2Bd',
      displayName: 'Sara Iqbal',
      status: 'busy',
      capabilities: ['res_fire_extinguisher_team', 'res_first_aid'],
      activeIncidentCount: 1,
    },
    location: { lat: 17.4512, lng: 78.4944 },
    distanceM: 1620,
    etaSec: 262,
    capabilityMatch: true,
    missingResources: [],
    staleLocation: false,
    rank: 2,
  },
  {
    responder: {
      uid: 'u_1Li4Op',
      displayName: 'K. Iyer',
      status: 'offline',
      capabilities: ['res_water_rescue'],
      activeIncidentCount: 0,
    },
    location: { lat: 17.4401, lng: 78.4822 },
    distanceM: 980,
    etaSec: 240,
    capabilityMatch: false,
    missingResources: ['res_fire_extinguisher_team'],
    staleLocation: true,
    rank: 3,
  },
];

/* -------------------------------------------------------------------------- */
/* Notifications                                                              */
/* -------------------------------------------------------------------------- */

export const MOCK_NOTIFICATIONS: readonly AppNotification[] = [
  {
    notificationId: 'ntf_01',
    type: 'incident_assigned',
    severity: 'critical',
    title: 'CG-7QK4M2 assigned to you',
    body: 'Yusuf Khan was assigned a road accident 640 m away. They are en route.',
    incidentId: 'r7Kp2mQ9xL4nT8vB3cD6',
    link: '/incidents/r7Kp2mQ9xL4nT8vB3cD6',
    read: false,
    createdAt: ago(2.2),
    actor: { uid: 'u_disp01', displayName: 'Meera Rao' },
  },
  {
    notificationId: 'ntf_02',
    type: 'critical_incident_alert',
    severity: 'critical',
    title: 'Critical incident: CG-4RT8W',
    body: 'Automated triage was unavailable, so this report is waiting for a person.',
    incidentId: 'r8Qw4zX1mV6nB2kD9sF3',
    link: '/incidents/r8Qw4zX1mV6nB2kD9sF3',
    read: false,
    createdAt: ago(2),
    actor: null,
  },
  {
    notificationId: 'ntf_03',
    type: 'sla_breached',
    severity: 'critical',
    title: 'Response target passed: CG-9ZZ1QP',
    body: 'Flooding on the lakeside road has been verified for 30 minutes with no responder assigned.',
    incidentId: 'r5Hj1vN8qC3mZ7tB2wE9',
    link: '/incidents/r5Hj1vN8qC3mZ7tB2wE9',
    read: false,
    createdAt: ago(4),
    actor: null,
  },
  {
    notificationId: 'ntf_04',
    type: 'duplicate_suggested',
    severity: 'warning',
    title: 'Possible duplicate: CG-3PL8QW',
    body: 'A similar fire report was submitted 3 minutes earlier, 310 m away, in the same category.',
    incidentId: 'r2Fw8nT4vX6mZ1qB9dK3',
    link: '/incidents/r2Fw8nT4vX6mZ1qB9dK3',
    read: false,
    createdAt: ago(7),
    actor: null,
  },
  {
    notificationId: 'ntf_05',
    type: 'incident_verified',
    severity: 'info',
    title: 'CG-7QK4M2 was verified',
    body: 'Meera Rao confirmed the report. Someone is being sent.',
    incidentId: 'r7Kp2mQ9xL4nT8vB3cD6',
    link: '/incidents/r7Kp2mQ9xL4nT8vB3cD6',
    read: true,
    createdAt: ago(3),
    actor: { uid: 'u_disp01', displayName: 'Meera Rao' },
  },
  {
    notificationId: 'ntf_06',
    type: 'responder_unavailable',
    severity: 'warning',
    title: 'Assignment withdrawn on CG-3PL8QW',
    body: 'The responder was not suitable for this incident and was unassigned.',
    incidentId: 'r2Fw8nT4vX6mZ1qB9dK3',
    link: '/incidents/r2Fw8nT4vX6mZ1qB9dK3',
    read: true,
    createdAt: ago(6),
    actor: null,
  },
];

/* -------------------------------------------------------------------------- */
/* Audit log                                                                  */
/* -------------------------------------------------------------------------- */

export const MOCK_AUDIT_ENTRIES: readonly AuditEntry[] = [
  {
    logId: 'log_01',
    actor: { uid: 'u_disp01', displayName: 'Meera Rao', role: 'dispatcher' },
    action: 'incident.status_change',
    entityType: 'incident',
    entityId: 'r7Kp2mQ9xL4nT8vB3cD6',
    incidentRef: 'CG-7QK4M2',
    summary: 'Status changed from assigned to en route',
    before: { status: 'assigned' },
    after: { status: 'en_route' },
    reason: null,
    requestId: 'req_3Gh6jK8lM0n',
    hasIpHash: true,
    createdAt: ago(1),
  },
  {
    logId: 'log_02',
    actor: { uid: 'u_disp01', displayName: 'Meera Rao', role: 'dispatcher' },
    action: 'incident.assign',
    entityType: 'incident',
    entityId: 'r7Kp2mQ9xL4nT8vB3cD6',
    incidentRef: 'CG-7QK4M2',
    summary: 'Assigned Yusuf Khan as responder',
    before: { assigneeUid: null },
    after: { assigneeUid: 'u_4Kd8sTn', distanceM: 640 },
    reason: 'Nearest verified responder with ambulance capability',
    requestId: 'req_8Ab2dF4hJ6k',
    hasIpHash: true,
    createdAt: ago(2.2),
  },
  {
    logId: 'log_03',
    actor: { uid: 'u_disp01', displayName: 'Meera Rao', role: 'dispatcher' },
    action: 'incident.merge',
    entityType: 'incident',
    entityId: 'r7Kp2mQ9xL4nT8vB3cD6',
    incidentRef: 'CG-7QK4M2',
    summary: 'Linked a duplicate report into this incident',
    before: { reportCount: 1 },
    after: { reportCount: 2 },
    reason: 'Same collision, reported twice 3 minutes apart',
    requestId: 'req_5Yc7uI9oP1r',
    hasIpHash: true,
    createdAt: ago(2.4),
  },
  {
    logId: 'log_04',
    actor: { uid: 'u_disp01', displayName: 'Meera Rao', role: 'dispatcher' },
    action: 'incident.status_change',
    entityType: 'incident',
    entityId: 'r7Kp2mQ9xL4nT8vB3cD6',
    incidentRef: 'CG-7QK4M2',
    summary: 'Status changed from triaged to verified',
    before: { status: 'triaged' },
    after: { status: 'verified' },
    reason: null,
    requestId: 'req_2Wx8pL0mN4q',
    hasIpHash: true,
    createdAt: ago(3),
  },
  {
    logId: 'log_05',
    actor: { uid: 'u_adm001', displayName: 'Arun Patel', role: 'admin' },
    action: 'responder.verify',
    entityType: 'responder',
    entityId: 'u_7Hq2Bd',
    incidentRef: null,
    summary: 'Verified Sara Iqbal as a responder',
    before: { verification: 'pending' },
    after: { verification: 'verified' },
    reason: 'Fire team lead, station 4 — certificate sighted',
    requestId: 'req_1Hs4bN6pQ8r',
    hasIpHash: true,
    createdAt: ago(60 * 9),
  },
  {
    logId: 'log_06',
    actor: { uid: 'u_adm001', displayName: 'Arun Patel', role: 'admin' },
    action: 'user.role_change',
    entityType: 'user',
    entityId: 'u_3Nm6Xc',
    incidentRef: null,
    summary: 'Changed role from citizen to responder',
    before: { role: 'citizen' },
    after: { role: 'responder' },
    reason: 'Volunteer sign-up, credentials seen',
    requestId: 'req_6Ft0zE4gV9w',
    hasIpHash: true,
    createdAt: ago(60 * 24 * 2),
  },
  {
    logId: 'log_07',
    actor: { uid: 'u_adm001', displayName: 'Arun Patel', role: 'admin' },
    action: 'config.update',
    entityType: 'config',
    entityId: 'app',
    incidentRef: null,
    summary: 'Changed the duplicate radius from 500 m to 650 m',
    before: { duplicateRadiusM: 500 },
    after: { duplicateRadiusM: 650 },
    reason: 'Too many road incidents split across the metro gate junction',
    requestId: 'req_9Xk2tD6fR1s',
    hasIpHash: true,
    createdAt: ago(60 * 24 * 4),
  },
  {
    logId: 'log_08',
    actor: { uid: 'system', displayName: 'CareGrid AI', role: 'system' },
    action: 'auth.login_failed',
    entityType: 'auth',
    entityId: 'unknown',
    incidentRef: null,
    summary: 'Failed sign-in attempt recorded',
    before: null,
    after: { provider: 'password', reason: 'INVALID_PASSWORD' },
    reason: null,
    requestId: 'req_2Wq8cL4vT0x',
    hasIpHash: true,
    createdAt: ago(35),
  },
];

/* -------------------------------------------------------------------------- */
/* Derived views                                                              */
/* -------------------------------------------------------------------------- */

export function mockUserByUid(uid: string): User | undefined {
  return MOCK_USERS.find((u) => u.uid === uid);
}

export function mockUserForRole(role: UserRole): User {
  const found = MOCK_USERS.find((u) => u.role === role && u.status === 'active');
  if (found) return found;
  const fallback = MOCK_USERS[0];
  if (!fallback) {
    throw new Error('MOCK_USERS must never be empty');
  }
  return fallback;
}

export function mockIncidentById(id: string): Incident | undefined {
  return MOCK_INCIDENTS.find((i) => i.incidentId === id || i.reference === id);
}

export const MOCK_DASHBOARD_TILES: DashboardTiles = {
  active: MOCK_INCIDENTS.filter((i) => !i.deletedAt && ['new', 'triaged', 'verified', 'assigned', 'en_route', 'on_scene', 'resolved'].includes(i.status)).length,
  unassigned: MOCK_INCIDENTS.filter((i) => !i.deletedAt && i.assignee === null && i.status !== 'closed').length,
  critical: MOCK_INCIDENTS.filter((i) => !i.deletedAt && i.urgency === 'critical').length,
  slaBreached: MOCK_INCIDENTS.filter((i) => !i.deletedAt && i.slaState === 'breached').length,
  availableResponders: MOCK_RESPONDERS.filter((r) => r.status === 'available' && r.verification === 'verified').length,
  staleResponderLocations: MOCK_RESPONDERS.filter((r) => r.staleLocation).length,
  potentialDuplicates: MOCK_INCIDENTS.filter((i) => i.duplicateStatus === 'potential_duplicate').length,
  aiNeedsReview: MOCK_INCIDENTS.filter((i) => !i.deletedAt && i.aiNeedsReview).length,
};

export const MOCK_SYSTEM_HEALTH: SystemHealth = {
  firestoreReads: 1284,
  listenersActive: 5,
  listenersMax: 8,
  aiSuccessPct: 97.4,
  aiFallbackPct: 2.6,
  maintenanceEnabled: false,
};

/* -------------------------------------------------------------------------- */
/* Analytics — clearly labelled demo data                                     */
/* -------------------------------------------------------------------------- */

export const MOCK_ANALYTICS: Analytics = {
  range: {
    from: '2026-09-19',
    to: '2026-09-26',
    timezone: 'Asia/Kolkata',
    granularity: 'day',
    source: 'rollup',
    advisory: null,
  },
  totals: {
    total: 148,
    active: 11,
    critical: 26,
    high: 41,
    medium: 55,
    low: 26,
    resolved: 119,
    cancelled: 6,
    falseAlarm: 9,
    meanTimeToVerifySec: 214,
    meanTimeToDispatchSec: 402,
    meanTimeToResolveSec: 1480,
    slaCompliancePct: 88.4,
    duplicateRatePct: 12.1,
    aiFallbackRatePct: 3.2,
    meanAiConfidence: 0.79,
    reportsPerIncident: 1.24,
  },
  byCategory: [
    { category: 'traffic_accident', count: 41, critical: 9 },
    { category: 'heatwave', count: 27, critical: 2 },
    { category: 'medical', count: 22, critical: 11 },
    { category: 'infrastructure', count: 18, critical: 0 },
    { category: 'flood', count: 14, critical: 3 },
    { category: 'community_aid', count: 11, critical: 0 },
    { category: 'fire', count: 8, critical: 4 },
    { category: 'severe_storm', count: 4, critical: 0 },
    { category: 'missing_person', count: 2, critical: 1 },
    { category: 'violence_crime', count: 1, critical: 1 },
    { category: 'other', count: 0, critical: 0 },
  ],
  trend: [
    { bucket: '2026-09-19', created: 18, resolved: 15, critical: 3 },
    { bucket: '2026-09-20', created: 21, resolved: 19, critical: 4 },
    { bucket: '2026-09-21', created: 16, resolved: 17, critical: 2 },
    { bucket: '2026-09-22', created: 24, resolved: 20, critical: 5 },
    { bucket: '2026-09-23', created: 19, resolved: 21, critical: 3 },
    { bucket: '2026-09-24', created: 27, resolved: 22, critical: 6 },
    { bucket: '2026-09-25', created: 15, resolved: 18, critical: 2 },
    { bucket: '2026-09-26', created: 8, resolved: 7, critical: 1 },
  ],
  responseBuckets: [
    { label: '0–5 min', count: 22 },
    { label: '5–15 min', count: 31 },
    { label: '15–30 min', count: 28 },
    { label: '30–60 min', count: 19 },
    { label: '1–4 h', count: 11 },
    { label: 'Over 4 h', count: 4 },
  ],
  byUrgency: [
    { urgency: 'critical', p50Sec: 180, p90Sec: 420 },
    { urgency: 'high', p50Sec: 640, p90Sec: 1500 },
    { urgency: 'medium', p50Sec: 2280, p90Sec: 5400 },
    { urgency: 'low', p50Sec: 5400, p90Sec: 10800 },
  ],
  riskZones: [
    {
      zoneId: 'rz_9z4g0h_w38',
      centre: { lat: 17.4478, lng: 78.4874 },
      radiusM: 500,
      score: 78,
      severity: 'critical',
      incidentCount: 11,
      criticalCount: 5,
      dominantCategory: 'traffic_accident',
      computedAt: ago(60 * 7),
    },
    {
      zoneId: 'rz_9z4g2j_w38',
      centre: { lat: 17.4502, lng: 78.4931 },
      radiusM: 500,
      score: 61,
      severity: 'high',
      incidentCount: 8,
      criticalCount: 2,
      dominantCategory: 'heatwave',
      computedAt: ago(60 * 7),
    },
    {
      zoneId: 'rz_9z4g5n_w38',
      centre: { lat: 17.4412, lng: 78.4798 },
      radiusM: 500,
      score: 44,
      severity: 'medium',
      incidentCount: 5,
      criticalCount: 1,
      dominantCategory: 'flood',
      computedAt: ago(60 * 7),
    },
  ],
  responders: [
    { uid: 'u_4Kd8sTn', displayName: 'Yusuf Khan', assignments: 12, accepted: 11, avgResponseSec: 214 },
    { uid: 'u_7Hq2Bd', displayName: 'Sara Iqbal', assignments: 9, accepted: 9, avgResponseSec: 262 },
    { uid: 'u_2Ww9Kz', displayName: 'Ravi Menon', assignments: 7, accepted: 5, avgResponseSec: 388 },
  ],
};
